### ISSUE TITLE
Support of managing Droplets lifecycle

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [digitalocean/do-operator#14]
Hi, this seems like interesting project and I can probably help on working to support the droplets lifecycle.

**Comment by adamwg** [comment]
Hi @zufardhiyaulhaq! Thanks for the offer. The goal of this operator is to simplify consumption of DO products from Kubernetes workloads; we'd like to avoid using Kubernetes for generic resource management ([Crossplane](https://crossplane.io/) already does that well and supports DO).

Do you have a use-case for integrating droplets into your Kubernetes workloads? Interested to hear about it if so and understand how this operator can help.

**Comment by zufardhiyaulhaq** [comment]
Hi @adamwg Thanks just know about Crossplane, will try to check that.
