### ISSUE TITLE
Deleting Database objects orphans secrets

### ISSUE THREAD

**Issue by jhgaylor** [digitalocean/do-operator#5]
I noticed I have some secrets in my cluster that remain after I deleted the database that created the secret.

This can be fixed by using [controllerutil.SetControllerReference](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#SetControllerReference) to mark the secret as "owned" by the database and then kubernetes will garbage collect them.

**Comment by jhgaylor** [comment]
It looks like because the secrets aren't getting deleted that when you create a database, by the same name as the one that was deleted to create the orphan, that the secret does not get updated.

**Comment by adamwg** [comment]
We have built a brand new version of the do-operator, which does set owner references on secrets correctly. Closing this out.
